services:
  - type: web
    name: ssl-payment-getway
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      - key: APP_NAME
        value: SSL Payment Gateway

      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_KEY
        generateValue: true

      - key: APP_URL
        sync: false

      # PostgreSQL
      - key: DB_CONNECTION
        value: pgsql

      - key: DB_HOST
        fromDatabase:
          name: ssl-payment-db
          property: host

      - key: DB_PORT
        fromDatabase:
          name: ssl-payment-db
          property: port

      - key: DB_DATABASE
        fromDatabase:
          name: ssl-payment-db
          property: database

      - key: DB_USERNAME
        fromDatabase:
          name: ssl-payment-db
          property: user

      - key: DB_PASSWORD
        fromDatabase:
          name: ssl-payment-db
          property: password

      # SSLCommerz
      - key: SSLCOMMERZ_MODE
        value: sandbox

      - key: SSLCOMMERZ_STORE_ID
        sync: false

      - key: SSLCOMMERZ_STORE_PASSWORD
        sync: false


databases:
  - name: ssl-payment-db
    databaseName: sslcz
    user: sslcz
    plan: free