services:
  - type: web
    name: ssl-payment-getway
    runtime: docker
    plan: free

    dockerfilePath: ./Dockerfile

    healthCheckPath: /

    envVars:
      - key: APP_NAME
        value: SSL Payment Gateway

      - key: APP_ENV
        value: production

      - key: APP_DEBUG
        value: "false"

      - key: APP_KEY
        generateValue: true

      - key: APP_URL
        sync: false

      # MySQL
      - key: DB_CONNECTION
        value: mysql

      - key: DB_HOST
        value: sql12.freesqldatabase.com

      - key: DB_PORT
        value: "3306"

      - key: DB_DATABASE
        value: sql12837097

      - key: DB_USERNAME
        value: sql12837097

      - key: DB_PASSWORD
        sync: false

      # SSLCommerz
      - key: SSLCOMMERZ_MODE
        value: sandbox

      - key: SSLCOMMERZ_STORE_ID
        sync: false

      - key: SSLCOMMERZ_STORE_PASSWORD
        sync: false